### ISSUE TITLE
Server is unreachable

### ISSUE THREAD

**Issue by eson57** [mkiol/SendToJolla#3]
I was very excited about the idea of this app, but I can't make it work.
As topic says...  "Server is unreachable", is all I get from client. I`ve tried to change both URL and port number, but it makes no difference. App says "Server is listening on port 9292" and client is configured with correct URL. SalfishOS version is 1.1.2.15. Firefox version 35.0.1.

**Comment by mkiol** [comment]
Are you sure that phone is accessible from within your PC network? Can you "ping" phone's IP?

What is your "server URL" value?

**Comment by eson57** [comment]
Yes, I'm sure. I can SSH my phone from main PC without problem, and I also remote my Kodi HTPC from phone (Kodimote).
Server URL is http://192.168.1.5:9292/M30CS. Makes no difference if generating new URL.

**Comment by mkiol** [comment]
Try to type "server URL" in the Firefox address bar. You should see blank page and new "Unknown request.." entry in the SendToJolla's Log. Do you see anything like that?

**Comment by eson57** [comment]
No! I get "Error on page load" from Firefox and nothing at all in SendToJolla's log.

**Comment by mkiol** [comment]
What says `netstat -ln`? Do you see SendToJolla listening port? 

In my case I can see:

```
[nemo@Jolla ~]$ netstat -ln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State      
tcp        0      0 127.0.0.1:53                0.0.0.0:*                   LISTEN      
tcp        0      0 :::9090                     :::*                        LISTEN      
tcp        0      0 ::1:53                      :::*                        LISTEN      
tcp        0      0 :::22                       :::*                        LISTEN      
udp        0      0 127.0.0.1:53                0.0.0.0:*                               
udp        0      0 ::1:53                      :::*                                    
```

SendToJolla is listening on 9090.

**Comment by eson57** [comment]
No, actually there is no sign of SendToJolla...

```
[nemo@Jolla ~]$ netstat -ln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State
tcp        0      0 127.0.0.1:53                0.0.0.0:*                   LISTEN
tcp        0      0 ::1:53                      :::*                        LISTEN
tcp        0      0 :::22                       :::*                        LISTEN
udp        0      0 127.0.0.1:53                0.0.0.0:*  
udp        0      0 0.0.0.0:41160               0.0.0.0:*  
udp        0      0 ::1:53                      :::*        
```

**Comment by eson57** [comment]
Hmm... don't know what I did, but suddenly it works.  :-)
Well, thanks for your time, and please let me know if you ever need Swedish translation for your apps.

**Comment by mkiol** [comment]
I'm glad it works. If you figured what was wrong, let me know.

... and thank you for willing to help me with translation. Much appreciated :-)
