### ISSUE TITLE
Not signed for latest Firefox

### ISSUE THREAD

**Issue by johnnydvc** [mkiol/SendToJolla#4]
Firefox blocks the plugin due to its new signing policy.
Any chances that this plugin will be signed, thus being usable again?
Greetings

**Comment by mkiol** [comment]
I'm trying... but since February add-on still awaits reviewing. It stuck in the waiting queue. I'm guessing, it is too niche and therefore none of the AMO reviewers wants to touch it :-(

**Comment by mkiol** [comment]
Good news :-)

Yesterday my preliminary review request has been approved and from now, add-on is signed and will appear in search results on [AMO](https://addons.mozilla.org).
